### ISSUE TITLE
Generating documentation from a chart with dependencies triggers exception

### ISSUE THREAD

**Issue by delvin1933** [jtama/helm-to-asciidoc#5]
The triggered exception is :

`Caused by: io.quarkus.qute.TemplateException: Rendering error in template [dependencies.adoc] line 6: Property "repository" not found on the base object "com.github.jtama.Dependency" in expression {dependency.repository}`

Version used : helm-to-asciidoc-0.1.2-SNAPSHOT-linux-x86_64.tar.gz

**Comment by jtama** [comment]
This is caused by records not beeing correctly registered for native compilation.
