### ISSUE TITLE
Doc broken when generating from basic template

### ISSUE THREAD

**Issue by delvin1933** [jtama/helm-to-asciidoc#6]
Version used: helm-to-asciidoc-0.1.2-SNAPSHOT-linux-x86_64.tar.gz

Helm version : `version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}`

Step to reproduce:

```shell
helm create test-chart
cd test-chart
helm-to-asciidoc -c Chart.yaml -v values.yaml -o output.adoc
```

the rendered asciidoc file seems broken after the `service` section

**Comment by jtama** [comment]
There's a missing line break here : https://github.com/jtama/helm-to-asciidoc/blob/fa4b81c07e27b29ab76b753294b33e51f60cabc4/src/main/resources/templates/section.adoc?plain=1#L11
